# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Launch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: lint
      run: |
        npm ci
        npm test
    - name: build site
      run: npm start
    - name: Commit files
      run: |
        mv public/* .
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Site update"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:  
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
